dist: xenial

language: minimal

stages:
  - "unit tests"
  - "end-to-end tests"
  - "build image"

env:
  global:
    - CHANGE_MINIKUBE_NONE_USER=true

jobs:
  include:
    - stage: "unit tests"
      language: python
      python:
        - "3.7"
      install:
        - pip install -r requirements.txt
      script:
        - make test
    - stage "end-to-end tests"
      env:
        - KUBE_VERSION=1.15.10 ISTIO_VERSION=1.4.3
      script:
        - test/test.sh
    - env:
        - KUBE_VERSION=1.15.10 ISTIO_VERSION=1.4.6
      script:
        - test/test.sh
    - env:
        - KUBE_VERSION=1.16.0 ISTIO_VERSION=1.4.3
      script:
        - test/test.sh
    - env:
        - KUBE_VERSION=1.16.0 ISTIO_VERSION=1.4.6
      script:
        - test/test.sh
    - stage: "build image"
      script:
        - if [ "$TRAVIS_BRANCH" == "master" ]; then
            echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin;
            if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
              export IMG="iter8/iter8-trend:$TRAVIS_BUILD_NUMBER-PR_$TRAVIS_PULL_REQUEST";
              echo "Building PR Docker image = $IMG";
              make docker-build;
              make docker-push;
            else
              export IMG="iter8/iter8-trend:$TRAVIS_BUILD_NUMBER-$TRAVIS_COMMIT";
              echo "Building PR Docker image = $IMG";
              make docker-build;
              make docker-push;
              LATEST="iter8/iter8-trend:latest";
              docker tag $IMG $LATEST;
              export IMG=$LATEST;
              make docker-push;
            fi
          fi
