dist: xenial

language: minimal

stages:
  - "unit tests"
  - name: "build image"
    if: branch = master

jobs:
  include:
    - stage: "unit tests"
      language: python
      python:
        - "3.7"
      install:
        - pip install -r requirements.txt
      script:
        - make test
    - stage: "build image"
      script:
        - if [ "$TRAVIS_BRANCH" == "master" ]; then
            echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin;
            export IMG="iter8/iter8-trend:$TRAVIS_BUILD_NUMBER-PR_$TRAVIS_PULL_REQUEST";
            echo "Building PR Docker image = $IMG";
            make docker-build;
            make docker-push;
            LATEST="iter8/iter8-trend:latest";
            docker tag $IMG $LATEST;
            export IMG=$LATEST;
            make docker-push;
          fi
