dist: xenial

language: minimal

stages:
  - "unit tests"
  - "end-to-end tests"
  - "build image"

# Define yaml anchor to be reused across testing matrix
_end_to_end_script: &end_to_end_script
  script:
    - test/install-minikube.sh
    - test/sanity-check.sh
    - test/install-istio.sh
    - test/install-iter8.sh
    - test/install-iter8-trend.sh
    - test/e2e-test.sh

jobs:
  include:
    - stage: "unit tests"
      language: python
      python:
        - "3.7"
      install:
        - pip install -r requirements.txt
      script:
        - make test
    - stage: "end-to-end tests"
      env: KUBE_VERSION=v1.15.10 ISTIO_VERSION=1.4.3
      <<: *end_to_end_script
    - env: KUBE_VERSION=v1.15.10 ISTIO_VERSION=1.4.6
      <<: *end_to_end_script
    - env: KUBE_VERSION=v1.16.0 ISTIO_VERSION=1.4.3
      <<: *end_to_end_script
    - env: KUBE_VERSION=v1.16.0 ISTIO_VERSION=1.4.6
      <<: *end_to_end_script
    - stage: "build image"
      script:
        - test/build-image.sh
