# Default values for iter8-trend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: haih/iter8-trend
  tag: latest
  pullPolicy: Always

namespace: iter8

iter8Config:
  # Target port used by iter8-trend server
  iter8TrendPort: 8888

nameOverride: "iter8-trend"
fullnameOverride: "iter8-trend"

service:
  type: ClusterIP
  port: 8888

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
