apiVersion: v1
kind: Service
metadata:
  name: iter8-trend
  namespace: iter8
  labels:
    app: iter8-trend
spec:
  type: ClusterIP
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
      name: http
  selector:
    app: iter8-trend
