apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: iter8-clusterrole
rules:
- apiGroups:
  - iter8.tools
  resources:
  - experiments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - iter8.tools
  resources:
  - experiments/status
  verbs:
  - get
