apiVersion: v1
kind: Service
metadata:
  name: {{ include "iter8-trend.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "iter8-trend.name" . }}
    helm.sh/chart: {{ include "iter8-trend.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.iter8Config.iter8TrendPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "iter8-trend.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
